### ISSUE TITLE
Forward air conditioning in HomeKit

### ISSUE THREAD

**Issue by johngrinders** [XattSPT/com.melcloud#1]
Hey. Thank you very much for the plugin !!! Waited a long time. Everything works fine, now I'm starting to do automation. The only question is: I tried to forward the air conditioner through the HomeyKit plug-in in HomeKit, but I encountered that the device in HomeKit shows the correct temperature, makes it possible to control the on and modes, but does not control them.

**Comment by XattSPT** [comment]
I've sent a new version with Homeykit compability. I supose it will be aproved in a few days. 
It's necessary to delete devices and re-add them to get new capability "Homekit Thermostat"

Do not hesitate to post here if you have any suggestion.

**Comment by johngrinders** [comment]
Thank you very much!!! I will wait for the new version.
