### ISSUE TITLE
Additional Improvements

### ISSUE THREAD

**Issue by kajo23** [XattSPT/com.melcloud#10]
Hi.  Long time no replay from my side because I don't have time for tests. 
I am still with Test App V2.0.5. I see that official app is same version. I am afraid to install latest oficial App from Homey. 
I used plenty of rules to heat my house and i am Happy at the moment 

BUG: Advanced Settings: Eco Hot Water (DHW) - "Yes to No" and "No to Yes' after Confirmation do NOT works. Return back to previous state.

TRIGGER: Operation Mode Changed
ACTION: Operation Mode returns only those 4 states: Off, DHW-Heating, Heating, Legionela
SUGGESTION:  add DEFROST, maybe also rest of the operation modes. 

I want to Donate you for the job you did. But I do NOT see Donate link on the Homey page.
Regards

_Originally posted by @kajo23 in https://github.com/XattSPT/com.melcloud/issues/8#issuecomment-595058086_

**Comment by XattSPT** [comment]
I'll take a look on your report.

Unfortunately now I can't test with a Heat-pump. If you can share your unit
through Melcloud should be really helpful. I will not touch any
configuration on your unit, but I need to receive data from the unit to see
how works the app.

If you update to official App, I'm 99+% sure nothing will change, just
download app, without deleting test one and all will be ok (is exactly the
same version, so at your choice).

I'd put a link to Donate on homey app (the link is above part of page, I
think) or use paypal.me/XattSPT

thnks,

G.


Missatge de kajo23 <notifications@github.com> del dia dg., 29 de març 2020
a les 17:02:

**Comment by kajo23** [comment]
I can share MELCloud. I can restrict it only to see what's going on. I need your email to do that.

**Comment by XattSPT** [comment]
For me it’s enought with restriction.

Gerard.ricart@gmail.com

El dg, 29 març 2020 a les 17:53 kajo23 <notifications@github.com> va
escriure:

**Comment by kajo23** [comment]
BTW it is also good to remove start/stop of the machine on device click because of miss click. It is much better to go into screens and there to start/stop machine

**Comment by XattSPT** [comment]
Received.

I'll take a look to all theese things, and I'll notify when I publish a new version for your test.

**Comment by kajo23** [comment]
Reminder. I see new update but suggestions I made were not done.

**Comment by XattSPT** [comment]
@kajo23 I've implemented one (SUGGESTION: add DEFROST, maybe also rest of the operation modes.) 

I have the rest on  mind but have little time theese days. I'll do my best to implement, but some of them needs to remake some parts and have to do it with time.

Published upgrade was to update basically some malfuncion on AC devices. 

Thanks for your patience,

G.

**Comment by kajo23** [comment]
Hi today I tried to switch from heating to cooling but machine goes back to heating after 2 min. I stop app and machine is working fine.

**Comment by XattSPT** [comment]
On which version are you?

El dl, 29 juny 2020 a les 22:41 kajo23 <notifications@github.com> va
escriure:

**Comment by kajo23** [comment]
2.0.9 Latest

**Comment by XattSPT** [comment]
On test version this issue has been already solved. Thanks for your report.

Hope to publish soon, just finishing some adjustments, but tou are free to
use test one.

El dl, 29 juny 2020 a les 22:47 kajo23 <notifications@github.com> va
escriure:

**Comment by kajo23** [comment]
I have installed version 2.0.11

When I set:
ADVANCED SETTINGS > OPERATION MODE > Cooling is set but does not send command to server.

**Comment by kajo23** [comment]
Shell you make an update 
App set pump to Heating every time but I need Cooling at this time

**Comment by kajo23** [comment]
You miss to add following:
OperationModeZone1 and OperationModeZone2
   0 - Heating Room
   1 - Heating Flow
   2 - Heating Curve
   3 - Cooling Room
   4 - Cooling Flow

EcoHotWater
   1 - On (enable)
   2 - Off (disable)

Hope this will help you a lot. Please update to test.

**Comment by foni73** [comment]
Hi

I can't find any flowcard for AC room temperature. Will that be available in the future?

**Comment by XattSPT** [comment]
@foni73 I don't undestand your question. Flowcards for temperature (trigger, condition and action) are available... What kind of flowcards are you looking for?

**Comment by XattSPT** [comment]
@foni73 "temperature" is room temperature. Set temperature is device set temperature. I think you are looking for temperature. this is available on condition and trigger. Obiously is not available on action.

**Comment by foni73** [comment]
I am new to Homey, so maybe looking in the wrong place, but I can't seem to fin condition or trigger for the actual temperature in the room. There is a card for temperature change
![image](https://user-images.githubusercontent.com/71647230/93771152-6c554480-fc1d-11ea-90ce-7a38026094c9.png)
And fanspeed etc. 
![image](https://user-images.githubusercontent.com/71647230/93771571-fc938980-fc1d-11ea-88f5-5522b8851af0.png)

Any suggetion how/where i find the current romm temp in C?

**Comment by foni73** [comment]
Would like it to use it like if temp > 25 cool. If temp < 18 heat. Instead of using the AC auto mode.
