### ISSUE TITLE
Heatpump adding, times out...

### ISSUE THREAD

**Issue by gooooba** [XattSPT/com.melcloud#11]
I deleted the app and then reinstalled. Now I'm not finding any HeatPump. after entering email and credentials it goes to searching, then times outs.

**Comment by XattSPT** [comment]
Dear @gooooba. I've tried a couple of times and it works in my case... Please double check usr/pswd... 
It is in my to-do list to improve login process to return problem system have on login process, but have no time theese days... 
Do not hesitate to contact me if I can do anything for U... 

PD: sorry for late response.

**Comment by gooooba** [comment]
Tried with correct or incorrect password it is the same....timeout in 30 seconds....

I guess I will need to wait for improved login process. When you have the time 😊

**Comment by XattSPT** [comment]
@gooooba it there the posibility to share your melclud as a guest to me? I think I've discovered the problem, but i should need to test it. I have time this weekend, and I'll try to solve it.

I think there is some problem on detecting devices depending on building structure on Melcloud, but I need to check it.

Thanks in advance,

G.

**Comment by XattSPT** [comment]
@gooooba I've published a test version with improved login process

https://homey.app/a/com.mecloud/test/

**Comment by XattSPT** [comment]
@gooooba can u add devices now?

**Comment by XattSPT** [comment]
No news... I suppose you can add them now. 

If not, one question... have you changed your mobile? some users having problems caused mainly by their phone, if they try with other phone it works...

**Comment by XattSPT** [comment]
1)Today seems melcloud is down. Are Melcloud app working?

2) some users have solved using other movile/tablet. It seems do not work
with some devices but it is only a suppose I can not reproduce this error.
Can you try with other device?




El dj, 3 set 2020 a les 14:15 pontussandgren <notifications@github.com> va
escriure:

**Comment by pontussandgren** [comment]
Thanks for your prompt answer :-). I have got my heatpumps installed yesterday and the MelCloud app worked this morning but no longer. As for now I assume it is related to that.

**Comment by langfjord** [comment]
Having the same issue. Been checking username/password and trying the new test app. I have access to Melcloud app without problem and can control the heat pump from there. Trying to add Heat Pump as new device in Homey results in the same timeout message as above. The new app did now make any difference for me. Says version 2.0.11. Will retry tomorrow in case this is an issue with newly registered devices or something is temporary down at Melcloud.

**Comment by XattSPT** [comment]
Try to add from different device (phone). Some phones seems to have some
bug.

I’m stil investigating on this issue...

Thanks for tour report!



El dv, 30 oct 2020 a les 19:00 langfjord <notifications@github.com> va
escriure:

**Comment by gooooba** [comment]
> @gooooba it there the posibility to share your melclud as a guest to me? I think I've discovered the problem, but i should need to test it. I have time this weekend, and I'll try to solve it.
> 
> I think there is some problem on detecting devices depending on building structure on Melcloud, but I need to check it.
> 
> Thanks in advance,
> 
> G.

Hi, still not working. I can share guest access if you still like to test

**Comment by XattSPT** [comment]
Dear @gooooba received. I’ll do a couple of tests on weekend.

**Comment by XattSPT** [comment]
@gooooba I can add it without any problem... 

Have you tried to add throught other phone?

Or you can try to do through https://developer.athom.com/ 

do there and Login. Go Tools and Pairing.
Add a Melcloud device and you should see it there 

![image](https://user-images.githubusercontent.com/38588531/100521892-e74f5400-31a6-11eb-8c12-00d03d4b5b17.png)

Tell me if any of theese option works.

**Comment by gooooba** [comment]
Via developer page done without a problem...I guess there is a problem with my phone.Any idea what could be wrong. I did try uninstall/reinststall allready.The important thing is that now it is added 😊Br,DusanPoslano iz naprave Galaxy
-------- Izvirno sporočilo --------Od: Gerard Ricart <notifications@github.com> Datum: 28. 11. 20  18:25  (GMT+01:00) Za: "XattSPT/com.melcloud" <com.melcloud@noreply.github.com> Kp: gooooba <dd@vklop.com>, Mention <mention@noreply.github.com> Zadeva: Re: [XattSPT/com.melcloud] Heatpump adding, times out... (#11) 
@gooooba I can add it without any problem...
Have you tried to add throught other phone?
Or you can try to do through https://developer.athom.com/
do there and Login. Go Tools and Pairing.
Add a Melcloud device and you should see it there

Tell me if any of theese option works.

**Comment by XattSPT** [comment]
Hope to hear that. It seems that some phones are not correctly working. 

For next users, which phone do u have?

Pd: do not forget to remove invitation on melcloud.

**Comment by gooooba** [comment]
Samsung S9.The adding of devices in melcloud app used to work with no problem on this phone... so I guess it is not a phone itself. Maybe factory reset would help... but to much work 😁Poslano iz naprave Galaxy
-------- Izvirno sporočilo --------Od: Gerard Ricart <notifications@github.com> Datum: 28. 11. 20  20:53  (GMT+01:00) Za: "XattSPT/com.melcloud" <com.melcloud@noreply.github.com> Kp: gooooba <dd@vklop.com>, Mention <mention@noreply.github.com> Zadeva: Re: [XattSPT/com.melcloud] Heatpump adding, times out... (#11) 
Hope to hear that. It seems that some phones are not correctly working.
For next users, which phone do u have?
Pd: do not forget to remove invitation on melcloud.
