### ISSUE TITLE
Set Water Tank Temp in flow

### ISSUE THREAD

**Issue by ChristerSjo** [XattSPT/com.melcloud#12]
I can´t find any possibility to set Water Tank Temp and Eco Hot Water (DHW) in a flow in Homey. Am I missing something?

**Comment by XattSPT** [comment]
Dear @ChristerSjo, probably not missing anything. 

I've never implemented those functions, as testers who helped me told me this functions where not ususal to change. 

I'll try to implement them, as soon I have some free time.

**Comment by ChristerSjo** [comment]
Thanks,

I will use it during the winter and raise the temperature (for the hot water to last 24 hours) and then force it to heat the hot water when the electricity price is low at night. Then set the temperature back.

I have solar panels that heat the hot water in sunny weather in the summer. I could look at the weather forecast for the coming day and when it is going to be cloudy weather warm the hot water when the electricity price is low at night in the same way as winter time

**Comment by XattSPT** [comment]
Dear @ChristerSjo,

I've published a test app with flowcards you suggested. 
You can try if you want. If something is not going correctly please tell me here.
You can try on your homey here: 
    https://homey.app/es-es/app/com.mecloud/MelCloud/test/

P.D.: I've not a HP, so I can not do all test I want.

**Comment by ChristerSjo** [comment]
Hi,

 

Thank, yes now i can change Hot water temp, but in this version I can´t see the frequency in the app and in Insights it´s zero all the time (since I install this version yesterday).

 

Best regards,

Christer

 

Från: Gerard Ricart <notifications@github.com> 
Skickat: den 3 maj 2020 18:55
Till: XattSPT/com.melcloud <com.melcloud@noreply.github.com>
Kopia: ChristerSjo <christer@sjostrom.biz>; Mention <mention@noreply.github.com>
Ämne: Re: [XattSPT/com.melcloud] Set Water Tank Temp in flow (#12)

 

Dear @ChristerSjo <https://github.com/ChristerSjo> ,

I've published a test app with flowcards you suggested.
You can try if you want. If something is not going correctly please tell me here.
You can try on your homey here:
https://homey.app/es-es/app/com.mecloud/MelCloud/test/

P.D.: I've not a HP, so I can not do all test I want.

**Comment by XattSPT** [comment]
@ChristerSjo I've published a new version https://homey.app/a/com.mecloud/test/

Hope this solve missing existing parts :)

any additional coments are welcomed. 

One question: in your opinion, Fored Water should be on "buttons" area or better on "settings"??

**Comment by ChristerSjo** [comment]
Hi,

 

Now it seems to work 😊

 

In my opinion Force water should be on “button” area.

 

Have a good day!

/Christer

 

Från: Gerard Ricart <notifications@github.com> 
Skickat: den 9 maj 2020 17:47
Till: XattSPT/com.melcloud <com.melcloud@noreply.github.com>
Kopia: ChristerSjo <christer@sjostrom.biz>; Mention <mention@noreply.github.com>
Ämne: Re: [XattSPT/com.melcloud] Set Water Tank Temp in flow (#12)

 

@ChristerSjo <https://github.com/ChristerSjo>  I've published a new version https://homey.app/a/com.mecloud/test/

Hope this solve missing existing parts :)

any additional coments are welcomed.

One question: in your opinion, Fored Water should be on "buttons" area or better on "settings"??
