### ISSUE TITLE
AC unit koppelen werkt niet time out

### ISSUE THREAD

**Issue by grolsch1986** [XattSPT/com.melcloud#13]
Ik krijg mij ac unit niet gekoppeld krijg elke keer time out.
Inloggegevens zijn correct wat kan ik hier aan doen

**Comment by XattSPT** [comment]
Dear @grolsch1986,

  I will try to solve it, some users having this problem.

   Which structure (building/floors/zones) do you have in melcloud?

Thanks,

G

**Comment by grolsch1986** [comment]
Ik heb geen gebouw zones en vloeren ingesteld

**Comment by grolsch1986** [comment]
![Screenshot_20200508_214945_mitsubishi wifi android mitsubishiwifiapp](https://user-images.githubusercontent.com/37909395/81443587-f7a1d200-9175-11ea-8ae9-7bd201885edc.jpg)

**Comment by XattSPT** [comment]
Thanks.

If you can invite me as guest on your melcloud (as guest only with read permision) should be very helpful for me to try to solve.

My email, is gerard.ricart@gmail.com

**Comment by grolsch1986** [comment]
Is zal is even kijken als ik dat kan vinden

**Comment by XattSPT** [comment]
El dv, 8 maig 2020 a les 21:56 grolsch1986 <notifications@github.com> va
escriure:

**Comment by grolsch1986** [comment]
Als goed is heb je een mail

**Comment by XattSPT** [comment]
Perfect, thank you.

I’ll check and come back to you in a couple of days!!


El dv, 8 maig 2020 a les 22:00 grolsch1986 <notifications@github.com> va
escriure:

**Comment by grolsch1986** [comment]
Suc6 en dank je

**Comment by XattSPT** [comment]
try this app with improved login process...

https://homey.app/a/com.mecloud/test/

I can add your device on homey, so probably the problem is on user/psswd.

**Comment by grolsch1986** [comment]
Perfect het is in 1 keer gelukt super service

**Comment by XattSPT** [comment]
You're welcome.

Do not forget to remove me as guest user.

If you want to review your valoration on homey appstore, feel free to do it ;)
