### ISSUE TITLE
Water Tank Temparature

### ISSUE THREAD

**Issue by ChristerSjo** [XattSPT/com.melcloud#17]
Water Tank Temperature in a insight is showing max 60 degrees C even if the temp is above. I have solar panels warming up the water in the summer and I reach +70 degrees a sunny day in 500 liters of water.

In the MelCloud app the correct temp are displayed

**Comment by XattSPT** [comment]
Thanks for your comment. It has been implented and will be available on next version.

Sorry for late reply and appliance.

Regards,

G.

**Comment by ChristerSjo** [comment]
Grate! Can you also make the degrees show increments of 0,5?

**Comment by XattSPT** [comment]
Which degrees?

I see them on .5 scheme 

![15E7410B-7178-40BA-94AD-E2954408C2E7](https://user-images.githubusercontent.com/38588531/100522281-cf2d0400-31a9-11eb-9d3b-30a8e6123fad.jpeg)

**Comment by ChristerSjo** [comment]
In the insights you only see the hole degrees.
