### ISSUE TITLE
On or Off status doesn’t update in Homey

### ISSUE THREAD

**Issue by TheBoink** [XattSPT/com.melcloud#18]
When switching on or off the airco using a remote control, the status doesn’t change in Homey. 

Resulting that flows that should trigger on the airco status don’t start.

**Comment by XattSPT** [comment]
@TheBoink today melcloud is on maintenence and system are not working so well. Have u got issues on past with this?

**Comment by TheBoink** [comment]
This is the first time I looked into this and noticed the status in Homey is not updating.

I’ll try it tomorrow again :)

Thanks for your fast reply!

Met vriendelijke groet,
Arthur.

On 3 Sep 2020, at 21:03, Gerard Ricart <notifications@github.com> wrote:

﻿

@TheBoink<https://github.com/TheBoink> today melcloud is on maintenence and system are not working so well. Have u got issues on past with this?

**Comment by TheBoink** [comment]
Hi,

I’m still seeing differences in on/off status.
The airco’s are all switched off. But I see this:

[cid:CFFF5479-7E93-4888-B43C-CF3816516089-L0-001][cid:A5AD6D93-7FDE-4B33-BDC3-E506055790F6-L0-001]

What can I do to help?

Met vriendelijke groet,
Arthur.

On 3 Sep 2020, at 21:07, Gerard Ricart <notifications@github.com> wrote:

﻿

@TheBoink<https://github.com/TheBoink> check Melcloud app if works homey app should work.

Do not hesitate to contact me if problem persists!
