### ISSUE TITLE
Not possible to change horizontal swing

### ISSUE THREAD

**Issue by ketillund** [XattSPT/com.melcloud#19]
I have a MSZ-LN35VGW (Kaiteki 6600)

When I try to change the position of the horizontal swing from a flow, nothing happens. However, what do happen is that the two vertical swings are aligned (if they are in different positions).
Adjusting the vertical swing from a flow works fine.

**Comment by XattSPT** [comment]
Please try test version, I’ve made some adjustments on horizontal swing.

Any feedback will be much appreciated.


El dc, 30 set 2020 a les 20:05 ketillund <notifications@github.com> va
escriure:

**Comment by ketillund** [comment]
How do I install the test version?

**Comment by XattSPT** [comment]
https://homey.app/es-es/app/com.mecloud/MelCloud/test/

**Comment by ketillund** [comment]
Thanks!
Can I have both the test version and the regular version installed at the same time, or should i uninstall the regular version?

**Comment by XattSPT** [comment]
U can have or the other.

If test version give U any problem, you can install previous one.

**Comment by ketillund** [comment]
The horizontal swing still don't work with the test version. 
In addition, when I had it in ventilation mode, and used a flow to change the horizontal swing, the heat pump turned itself off!

**Comment by XattSPT** [comment]
It will be published a new version in a couple of days (after approval) and hope works correct!
