### ISSUE TITLE
Missing functions vane control

### ISSUE THREAD

**Issue by Markus-art** [XattSPT/com.melcloud#2]
Thank you for good app.
Is it possible to integrate horizontal and vertical vane Control? Actually it is missing.
Wonderful would be, if the function fan speed and potentially vane control would be also available in HomeKit, using the app Homeykit.
Dears Markus

**Comment by XattSPT** [comment]
@Markus-art the functions you are looking for are available on Homey. At same screen of THERMOSTAT (select up part of screen and select which one you want).

Unfortunately it is not possible to bring then to homekit couse it is not available on Homekit functions! 

Tell me if you find them.

**Comment by Markus-art** [comment]
Thank you very much for your quick answer.
In homey, I have the functions: thermostat, on/off, fan speed, thermostat mode.
Vane Control I could not find.

**Comment by XattSPT** [comment]
On thermostat mode screen, you should be able to see other funcions clicking on title... and see a pickable list with Horizontal, Vertical and Homekit mode...

**Comment by Markus-art** [comment]
Yes thank you very much, I did not see it before. 
Is it possible to set the device update time to 1 minute because Mitsubishi changed their systems also to 1 minute update time?

**Comment by XattSPT** [comment]
It is possible to change it between 5 and 60. On settings (gear symbol on top-right at screen) and then advanced settings. I think it is enougth. The system updates after 2 minuts after every change. Then use set time to update the device every 5-60 min. Polling to much refreshes to server it is not good practice. 

It is pending by my side to create flow cards for changing Vane Control automatically from Homey. I hope to develop them soon.

**Comment by Markus-art** [comment]
Thank you very much. Best wishes.
