### ISSUE TITLE
Heat pump horizontal swing not working

### ISSUE THREAD

**Issue by baguesa** [XattSPT/com.melcloud#22]
Hi,
First, great app. Much appreciated! :)
Second. One bug that annoys me now in the winter when its colder. The horizontal swing doesn't work the way I want it to.
I'm using Homey Pro (Early 2019) 4.2.0. App 6.2.0.652. | Melcloud 2.0.9 | Mitsubishi MSZ-LN35VG
Thanks for any help! Happy to assist you with logs, testing and so on. Cheers!

Attachments below:
![homey_swing](https://user-images.githubusercontent.com/75122002/100442693-b852b880-30a8-11eb-901a-fb32abde41e7.PNG)
![melcloud_swing](https://user-images.githubusercontent.com/75122002/100442694-b8eb4f00-30a8-11eb-920b-7dfc9b07e79b.PNG)

**Comment by XattSPT** [comment]
Dear @baguesa thanks for your support!

I'll be publishing a new version in a couple of days and hope horizontal swing will work ok.

**Comment by baguesa** [comment]
Great news! Looking forward to test the new version.

**Comment by XattSPT** [comment]
you can test there https://homey.app/es-es/app/com.mecloud/MelCloud/test/

**Comment by baguesa** [comment]
Horizontal swing working for me in 2.0.12. Great success. Thank you!
