### ISSUE TITLE
Power usage Mitsubishi AC

### ISSUE THREAD

**Issue by Norjolo** [XattSPT/com.melcloud#23]
Hi.

Is it possible to get the power usage from an Mitsubishi AC in Athom Homey via MelCloud and your app or is it something you have planned?

Br
Jonny

**Comment by dozepih** [comment]
I have the same question

**Comment by osauser** [comment]
I see other smart home systems have plugins that provide the (estimated) power consumption through a more recent/detailed API, so hopefully this is something that can be implemented for Homey app.. +1 on the request!

**Comment by OlivierZal** [comment]
Hi @osauser, @dozepih and @Norjolo, I’m the new developer of the app, thanks for your suggestion, I will first fix some device control bugs and see what I can fetch from MELCloud API. In the meanwhile don’t hesitate to install this test version https://homey.app/fr-fr/app/com.mecloud/MELCloud/test/

**Comment by OlivierZal** [comment]
I close this issue since it is a duplicate with https://github.com/XattSPT/com.melcloud/issues/32, I'll keep you informed in this last one.
