### ISSUE TITLE
Waterflow on Ecodan?

### ISSUE THREAD

**Issue by lawrenz89** [XattSPT/com.melcloud#24]
You have made a great app. I got a air-to-water-heatpump (Ecodan) and at the bottom in the app I can see current frequency which is nice. 

Since you can display current frequency in the app (which also is found when I enter code 016 on my Ecodan), I was wondering if you can display the waterflow as well (witch is found when I enter code 540 on my Ecodan)? This gives me an indication on when I need to clean the filter.

Regards,
E

**Comment by Katatonz** [comment]
Bump on this one, I have access to the code list for more information with regards to outdoor unit. So one can evaluate gas temperatures and fan speeds. Would be nice to have the possibility to ask for different values from machine through you app as it is far better than mitsubishi own app

**Comment by OlivierZal** [comment]
Hi @lawrenz89 and @Katatonz, I’m the new developer of the app, thanks for your suggestion, I will first fix some device control bugs and see what I can fetch from MELCloud API. In the meanwhile don’t hesitate to install this test version https://homey.app/fr-fr/app/com.mecloud/MELCloud/test/

**Comment by OlivierZal** [comment]
Hi @lawrenz89 and @Katatonz: to be continued in https://github.com/OlivierZal/com.melcloud/issues/21
