### ISSUE TITLE
Forced Hotwater not triggered from flow

### ISSUE THREAD

**Issue by Datamupp** [XattSPT/com.melcloud#26]
Hi Gerard!  I found the problem with the forced hotwater not triggered from a flow.

In MelCloudHPDriver.js on the block starting at line 173 there was a couple of mixed up = and ==.

I also found another bug on line 168 that caused the actual temperature of the DHW to temporary drop when setting the max temp of the tank. I removed that line. If you update the app I would be glad if you also add the possibility to read, and view in insights, the max temperature of the tank.
![MelBug](https://user-images.githubusercontent.com/56507088/132293672-1847c51f-e5a3-418d-b0a3-cb2d3a4227c9.jpg)
I'm not sure about the importance of using semicolons but I also added a semicolon at line 29.

Thank you for making this great app!

Best regards
Håkan

**Comment by OlivierZal** [comment]
Hi @Datamupp, can you please install this test version https://homey.app/fr-fr/app/com.mecloud/MELCloud/test/ and tell me if the issue solved?

**Comment by Datamupp** [comment]
Hi @OlivierZal!  It worked like a charm :)  I've been using a modded version of v2.0.12 in which I fixed a few issues. In case you're interested in knowing what i've changed, and what I would like to change if I had the knowledge, just tell me :)

**Comment by OlivierZal** [comment]
Hi @Datamupp, glad to hear! And yes I’m curious 🧐😊

**Comment by Datamupp** [comment]
When setting the temperature for the watertank, the current temperature of the water was also temporary set to that temperature .  So if the current temperature is 47 with a target temp of 50, if I set the target temp to 54 the current temperature also goes to 54 and then dropping back to 47 in a few minutes.   I fixed this in MelCloudHPDriver.js around line 168 by removing the following line:  args.device.setCapabilityValue('watertank_temperature', value)

The temperature of the watertank never went below 40.   In app.json around line 466 I changed from 40 to 20.

I wanted decimals for the watertank temperature, just like the outside temp, so I added "decimals": 1, to app.json around line 462.

This is what I've fixed myself but there are other issues I would like to fix.  I would like to be able to view the current target temp of the watertank.  As for now I'm using homeyscript to read it from settings.tanktemperature.

There should also be a trigger for "Operation mode has changed" independent of what mode it changed to.  But there is also a bug allowing for a workaround. If I choose "Operation mode has changed to legionella" then this will trigger even if the mode isn't legionella, and then I can check the operation mode.

Just tell me if you need help testing things out, i'll be glad to help!  :)

**Comment by OlivierZal** [comment]
With pleasure, I’ve already fixed some of the issues you mentioned in a upcoming 3.0.7 (will be released for testing soon), but since I’ve only air-to-air and no air-to-water, so I need to ask some GitHub people for guest accesses 😊
