### ISSUE TITLE
Sync with Homey seems to freeze

### ISSUE THREAD

**Issue by whvanderpost** [XattSPT/com.melcloud#27]
Hi!
I've got a split unit that I control with the Mitsubishi MelCloud app (either on iOS or Windows). In Homey the MelCloud app does not seem to update the current state of the aircon units. The update time is set to 15 minutes, and when you use the Homey app to switch the unit on/off or change the temperature it keeps syncing for about a day and then stops.
Is this some kind of background/sleep mode that kicks in? And can this be changed so that the app keeps polling the current status?

**Comment by MTRKhn** [comment]
Same problem here. My heat pump ransomly stops reporting both hot and cold water temperature. Frequency is also not reported randomly. Therefore numbers are OK in the MelCloud app. Only the Homey integration got problems

**Comment by XattSPT** [comment]
I’ll take a look on that. I don’t know if recent update on melcoud units
have changed something. Thanks both for your report.

El dc, 8 des 2021 a les 15:48 MTRKhn ***@***.***> va escriure:

**Comment by whvanderpost** [comment]
> 

I must admit that I've had these Mitsubishi units since May this year and never got to reporting the issue, but it has been playing since the beginning so it won't be related to any recent updates.

**Comment by XattSPT** [comment]
Ok thanks for reporting.

One aditional question, which refresh time you got on advance setup? I
think problems are when this value is less than 2 or 3 minutes.

I’ll take a look and report to you any update.

El dc, 8 des 2021 a les 16:45 whvanderpost ***@***.***> va
escriure:

**Comment by whvanderpost** [comment]
It's on 15 minutes.

**Comment by MTRKhn** [comment]
If i remember correctly, there was an update of the firmware three weeks ago, the MelCloud app has a new "refresh" button and i assume it started with this update.

I can send you a diag report if needed.

**Comment by whvanderpost** [comment]
I've got the release notes of this new version.
![image](https://user-images.githubusercontent.com/2821657/145361181-ca21419f-533d-4a01-b29a-7a1e6d69dd1c.png)
