### ISSUE TITLE
Missing the "fan" option in mode-selection.

### ISSUE THREAD

**Issue by Zeeker86** [XattSPT/com.melcloud#28]
I use the Homey Pro to manage my smarthome and have connected my Melcloud to the system.
However, I wanted to change the setting in the heating-pump from "Heating" to "Fan" when it reached a temperature.
We use wood to heat the house when the electricity is priced high and want the fan to distribute the heat. 
That feature is not in Homey. I have it in the MelCloud app, but that app have no flows.
Is it possible to get that option. That would be very nice.

**Comment by XattSPT** [comment]
Fan mode is available on flows, please double check.

I understand you have not an ecodan, right?

El dg, 19 des 2021 a les 21:22 Zeeker86 ***@***.***> va
escriure:

**Comment by Zeeker86** [comment]
You are right.
I missed the card "Set full mode". Sorry about that.
Now it works fine.

I have a Mitsubishi Kaiteki 6600
