### ISSUE TITLE
Automation Melcloud in Homey

### ISSUE THREAD

**Issue by johngrinders** [XattSPT/com.melcloud#3]
Automation Melcloud in Homey
Hey. Melcloud works fine, there were no problems. Thanks again for the plugin.
It came to automation in Homey and was faced with the fact that in flow it is impossible, under certain conditions, to perform actions with the air conditioner, namely:
1. It is not possible to select operating modes such as "Fan" and "Dry" in flow, there are only "Auto", "Heat", "Cold" and off modes, which you can easily select Homey air conditioning in the device;
2. It is not possible to set "Fan power" in flow.
3. It’s not relevant for me, since I have a channel type air conditioner, but for other users who have air conditioning in the air conditioner, the shutters are rotary, they are also absent in flow.

**Comment by johngrinders** [comment]
Hey. Found one more problem. When I indicate in flow in the final action that the air conditioner is in AUTO mode, it eventually switches to FAN mode, although the air conditioner itself physically has AUTO mode. I also attach photos to questions in the first post.
![IMG_9409](https://user-images.githubusercontent.com/13437063/65747369-f4d3fe80-e109-11e9-8c1b-ca4e1acfef31.PNG)
![IMG_9410](https://user-images.githubusercontent.com/13437063/65747382-fd2c3980-e109-11e9-97dc-3d577f758aa0.PNG)

**Comment by johngrinders** [comment]
Hey. I want to remind myself again))) and about the problems that I found in the Melcloud plugin. The problem is that in FLOW I can not fully use or change all the available air conditioning modes. Namely, there are no "Fan" and "Dry" operating modes.
There is no way to change "Fan Power" in the stream.
Thank!!!

**Comment by kjellkk** [comment]
I copy the feedback from @johngrinders, to be able to set fan power in a flow would be good. However I am unsure if this relates to this app (MelCloud) or if it relates to Homey overall.

**Comment by XattSPT** [comment]
@johngrinders & @kjellkk I've published a test app with flowcards for non standard capabilities. 
Feel free to send me any failure or additional flowcards that could be added. 

https://homey.app/en-us/app/com.mecloud/MelCloud/test/
