### ISSUE TITLE
ACs cannot be fully controlled on Apple Home through HomeyKit

### ISSUE THREAD

**Issue by OlivierZal** [XattSPT/com.melcloud#30]
Hi,

I use HomeyKit to control my AC (from MELCloud app) through Apple Home, but many features which are available in Homey does not appear in Apple Home: e.g. although I can set the temperature and the heat/cool mode, I cannot set the fan power or vertical/horizontal position.

According to HomeyKit's developer, it's because MELCloud uses "custom capabilities". Is it possible to use the standard ones to make the AC controller fully work on Apple Home?

Regards

**Comment by XattSPT** [comment]
Hi,

Limitation is on Apple Homekit. It not has standard capabilities for fan
power, postion, … on an AC device, so it can not be sent to apple home.

Regards,

G.

El dl, 17 gen 2022 a les 12:44 Olivier Zalmanski ***@***.***>
va escriure:

**Comment by OlivierZal** [comment]
Thanks for the very quick answer.

I confess I'm not an expert in Apple HomeKit, but doesn't this page https://github.com/mongoose-os-apps/mel-ac-homekit (in particular videos in it) seem to indicate there can be a way to set those features?

**Comment by XattSPT** [comment]
It seems it can be done.

My Melcloud App uses all this information and connect melcloud to homey
with all theese data and more.

All data is available on Homey, if you want to see it on Homekit you should
check with app homey-homekit developer. This is not on my app scope.

El dl, 17 gen 2022 a les 16:58 Olivier Zalmanski ***@***.***>
va escriure:

**Comment by OlivierZal** [comment]
I understand.
