### ISSUE TITLE
Powerconsumtion and total Kwh.

### ISSUE THREAD

**Issue by Zeeker86** [XattSPT/com.melcloud#32]
Hi there.
I have a Mitsubishi Kaiteki 6600.
Is it possible to get a readout of power consumption since midnight ? (And a total consumption readout? )

**Comment by OlivierZal** [comment]
Hi @Zeeker86, I’m the new developer of the app, I’l first try to fix some bugs in device controls and then implement energy reports. In the meanwhile don’t hesitate to install this test version https://homey.app/fr-fr/app/com.mecloud/MELCloud/test/

**Comment by OlivierZal** [comment]
I will create an issue in the new project for a follow-up: it’s my next step.
