### ISSUE TITLE
Only 3 out of 5 wall units are visable

### ISSUE THREAD

**Issue by Tonlaar** [XattSPT/com.melcloud#34]
I'm a new user of Homey. Installed the MELcloud app. All went well but only 3 of the 5 airco wall units show up. I have 2 split-level systems, one with 2 wall units (only one is visible), a second one with 3 wall units (only two visible). I can switch the 3 units on and off (shows up in the log file), change the operation (warm, cool, fan etc.) I can change the temperature and the fan speed (all these actions don't show up in the log file). 

In Domoticz all 5 show up and update the status changes of the 3 visible in Homey MELcloud app .

Kind regards
Ton Laarhoven

**Comment by XattSPT** [comment]
Try to move all units on melcloud app to same floor, and then add them to
homey. It seems there is something wrong on adding code that make some
units not visible.

El dv, 4 febr 2022 a les 16:02 Tonlaar ***@***.***> va
escriure:

**Comment by Tonlaar** [comment]
The 3 working units are indeed on the 1st floor. The missing ones are on the ground floor
I'm not sure how to move the units to one floor.
I let you know what the effect is

**Comment by XattSPT** [comment]
On melcloud app, go to unit, and on options (top rigth …) move unit.

El ds, 5 febr 2022 a les 18:16 Tonlaar ***@***.***> va
escriure:

**Comment by Tonlaar** [comment]
Moved all units to the same floor and all 5 are visible now :-)

**Comment by XattSPT** [comment]
Thx for replying. Once added you can move them back if you want.

I’ll take a llok to solve that problem on next update.



El dg, 6 febr 2022 a les 13:17 Tonlaar ***@***.***> va
escriure:

**Comment by Tonlaar** [comment]
Moved them back to a separate floor and all is still working fine.
