### ISSUE TITLE
AND card "Fan speed does not equal x" return bad true/false

### ISSUE THREAD

**Issue by DavidDjerf** [XattSPT/com.melcloud#38]
I am creating an advanced flow for my heatpump I am struggling with the AND card for the Melcloud app.
I try to do a "AND Fan Speed does not equal Very High" but it always return true, even when the fan speed is set to Very high.
If I instead use a logic card to check "Fan Power is not exactly 5" it returns proper true/false.

**Comment by OlivierZal** [comment]
Hi @XattSPT, I got the resolution for this issue: https://github.com/XattSPT/com.melcloud/blob/9daeda6ed21ee28554a0808785c8836020563ad7/app.json#L2232

`fan_speed_conditioon` => `fan_speed_condition`

I am not allowed to make a pull request, can you please fix and deploy a new app version?

Thanks

**Comment by OlivierZal** [comment]
Hi @XattSPT, I got the resolution for this issue:

https://github.com/XattSPT/com.melcloud/blob/9daeda6ed21ee28554a0808785c8836020563ad7/app.json#L2232
`fan_speed_conditioon` => `fan_speed_condition`

Here is the fix: https://github.com/XattSPT/com.melcloud/pull/39

Can you please review, merge and deploy a new app version?

Thanks

**Comment by OlivierZal** [comment]
Hi @XattSPT, do you still maintain this Homey app? Do you want me to take over?

**Comment by OlivierZal** [comment]
Hi @XattSPT, did you have the occasion to see my PR?

Please note there are 2 commits:
- https://github.com/XattSPT/com.melcloud/pull/40/commits/c1d181b89e69bebc604359af3d289f5f9dba14be fixes the `fan_speed_condition`
- https://github.com/XattSPT/com.melcloud/pull/40/commits/e05bca94e3fe36c71c2e6ca6fb9b68fecc4d3105 fixes an issue with `fan` and `dry` full mode selection (which automatically switches to `auto` in some cases).
