### ISSUE TITLE
Cannot add second unit

### ISSUE THREAD

**Issue by FeKik** [XattSPT/com.melcloud#41]
Hi, I have AC unit with one heatpump and 2 AC units inside. I cannot add the second one to Homey. Is there a possibility to repair it? Thank you. BR, Miroslav

**Comment by XattSPT** [comment]
Try to move them on Melcoud App at same floor, then add them to homey app.

El dj, 1 set 2022 a les 13:54 FeKik ***@***.***> va escriure:

**Comment by XattSPT** [comment]
Check that: https://github.com/XattSPT/com.melcloud/issues/33

**Comment by FeKik** [comment]
Hi, Thanks, this is working now :)
