### ISSUE TITLE
Settings setpoint temperture heatpump is not syncing with the melcloud app

### ISSUE THREAD

**Issue by ronennieshow** [XattSPT/com.melcloud#45]
Just like the title

If i make a setting change in setpoint in the homey app ( change temperatuur ) it will not synq with the app
But homey does take the temp from the melcloud app. 

This is only with the heatpump 
Airco will work just fine

**Comment by ronennieshow** [comment]
Hi 

Love the update
The forced hot water function is working now for the ecodan heathpumps
But setting the set temp in homey for the thermostat stil is not taken over bij melcloud and the thermostat in my home. 
Also it is still not possible to switch the settings of the ecodan from operation mode and zone mode. This is also a thing that is not yet taken over bij the ecodan if you change the settings in homey. If you change the tempratur in the mel cloud app or on the thermostat it wil be taken over by the homey. Sow for now it is like a one way communication for homey. Changes extern are taken over but changes in homey don't take place in the system 

But already great thanks very nice to see people are looking in to it

**Comment by OlivierZal** [comment]
Hi @ronennieshow, can you please install this test version https://homey.app/fr-fr/app/com.mecloud/MELCloud/test/ and tell if the issue solved?

**Comment by ronennieshow** [comment]
Hi 
The change's on the thermostat is solved. 
If you change the temp in homey it is taken over by the thermostat and mel cloud. 
Great.

Other things i will test as soon as possible

**Comment by OlivierZal** [comment]
I'm glad to hear that!

Please don't hesitate to open a new issue on my GitHub in case of new issue.

**Comment by ronennieshow** [comment]
Changing zone operation mode has no effect. It does not change from room heating to flow heating or what so ever.

**Comment by OlivierZal** [comment]
This should have been fixed in test version 3.0.6 and have been successfully tested by some people, can you please provide me more details? (screenshots...).

**Comment by ronennieshow** [comment]
The change in tempratur is setpoint heatpump is working fine. 
It is the operation mode for the zone that does not respond to changes. 
Like setting from room to flow 
It wil stay in room modus. 
![image](https://user-images.githubusercontent.com/113858484/193312174-8aff1c1b-b830-4fa6-836d-4b92420aad76.png)


![image](https://user-images.githubusercontent.com/113858484/193312432-9227ff7e-2fb1-41e9-8c8f-b1df5908d301.png)

Cold water flow tempertur is synqing.
Hot water flow is synqing 
Water tank tempratur is synqing 

![image](https://user-images.githubusercontent.com/113858484/193312566-a8b21a63-9ed7-4e1b-8f3a-1ab4703b135a.png)

**Comment by OlivierZal** [comment]
Very strange since I tested it myself with a device for which a user added me as a guest to his MELCloud... Can I see a screenshot of your device settings in Homey?

**Comment by ronennieshow** [comment]
![image](https://user-images.githubusercontent.com/113858484/193315000-7c88e6c0-cbf3-4f9f-a46c-c1ea576b80c0.png)
![image](https://user-images.githubusercontent.com/113858484/193315083-266c7c5d-5a2c-412f-95ab-65bf9c11c175.png)

**Comment by OlivierZal** [comment]
If I well understand your screenshots:
- sync Homey => MELCloud does not work for you, either from a flow or a manual change
- sync MELCloud => Homey works

**Comment by ronennieshow** [comment]
Yes correct.

Temp changes from the homey to the melcloud in room modus do work fine at the moment. This isseu is fixt.

**Comment by ronennieshow** [comment]
And strange 
Now it is working. 
Could it be the case that if you have set the function from room to flow te first time form mel cloud ---> homey it put in the wright settings and values. 

Will check of it wil also works from a flow

**Comment by ronennieshow** [comment]
If i make the change for the zone operation mode in a flow changes are not taken over by mel cloud or homey

**Comment by OlivierZal** [comment]
It could an initialization issue: you need to sync from MELCloud first (because I migrated to Homey SDK 3) and it will be ok for good, or it can be a temporary sync issue (happens sometimes with MELCloud API). 

Don't hesitate to open a new issue if you find one.

**Comment by ronennieshow** [comment]
Well 
Your doing a great job.
And to be fair. it is not a commen thing to change the zone operation mode verry often
i am verry glad to have the forced hot water, the temp synqs and the thermostat changes fixt.

**Comment by OlivierZal** [comment]
I think I found the flow bug, I'll fix it in the next version.
