### ISSUE TITLE
Wrong github repo shown on Homey App Store

### ISSUE THREAD

**Issue by novicell-jhj** [XattSPT/com.melcloud#49]
That's so strange. Today my Homey updated my MELCloud app to 3.0.2. 
And that does not exists on this repo (newest is 2.0.12), but exists on a forked repo by Olivier Zal on https://github.com/OlivierZal/com.melcloud/tags

How the h... is that possible ? 
There are no approved pull requests from Oliver, just pending, and no other commits with new version numbers.

Because of the new version, all my heatpump integrations it broken. 

Please help !

![image](https://user-images.githubusercontent.com/113981570/192860116-a9d7c12b-a8da-49f8-9dbc-38d3c7348381.png)

![image](https://user-images.githubusercontent.com/113981570/192860211-0723ea1b-c79d-4221-9d09-8d009d992c0c.png)

**Comment by XattSPT** [comment]
Dear @novicell-jhj,
   I've no much time to continue developing apps so @OlivierZal has taken my work.
   Please add a new issue on his github and I'm sure he will try to solve.
Regards,
G.

**Comment by novicell-jhj** [comment]
Thanks for your message Gerard 👍 
Will @OlivierZal  get my message if I write in here ?

I have some big problems with my flows after I got the new version.

**Comment by OlivierZal** [comment]
Hi @novicell-jhj, yes :-)

Please share with me what's wrong (error messages you get, etc.) and I'll find out the bug and fix it ASAP.

**Comment by XattSPT** [comment]
@OlivierZal it seems you don't have enabled issues on your repository, so users coming from homey web cant open an issue.

**Comment by novicell-jhj** [comment]
> 

Yep, exactly @XattSPT. That's why I wrote here. Please activate issues @OlivierZal on your repo

**Comment by OlivierZal** [comment]
@novicell-jhj, done.

**Comment by OlivierZal** [comment]
@novicell-jhj, if you agree you can add my email olivier.zalmanski@me.com as a guest to your MELCloud account (with restricted access) so I can better debug your issues.
