### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by kalle-se** [XattSPT/com.melcloud#5]
I’ve tried installing it but only get the feedback from that no new devices was found. I’ve asked around in some Facebook groups but no one seems to have the same issue. Only difference I’ve found is that so far I’m the only one I’ve talked to whom has two Mitsubishi HERO connected to MELCloud. Any thoughts?

**Comment by XattSPT** [comment]
On melcloud app, do not organize them on rooms or floors or zones. Its a
bug pending by my side.

El ds, 9 nov 2019 a les 17:58 kalle-se <notifications@github.com> va
escriure:

**Comment by kalle-se** [comment]
I cant seem to find an option not to have them assigned to a floor. Tried putting them on the same floor but it didn't work. As it's a pain to install them without an wps capable router it would be nice not having to remove them and reinstall. 

Any ideas?

**Comment by XattSPT** [comment]
On mecloud app, select a device. Then actions move (you should accept to
change scenes) and then, do not divide on floors, do not divide on zones,
etc.

El ds, 9 nov 2019 a les 21:22 kalle-se <notifications@github.com> va
escriure:

**Comment by kalle-se** [comment]
It worked! Super thanks for the help! :)

**Comment by XattSPT** [comment]
😉

U’re welcome!

El ds, 9 nov 2019 a les 21:32 kalle-se <notifications@github.com> va
escriure:

**Comment by XattSPT** [comment]
New version updated that detects devices in any config on Melcloud, pending for Homey approval.
