### ISSUE TITLE
Vertical swing always set to automatic

### ISSUE THREAD

**Issue by DavidDjerf** [XattSPT/com.melcloud#9]
Whatever I try to set vertical swing it become automatic. If set to something else (manually) and then turn off the heatpump, it will also set to automatic.

It would be great if it was possible to trigger the pre defined quick modes that can be set using the Mitsubishi Melcloud app.

**Comment by XattSPT** [comment]
@DavidDjerf  which model do you have? how many options do you have?

I've tested on my device and I can't reproduce your error... any aditional information will be welcomed!

**Comment by DavidDjerf** [comment]
The one I have is "MSZ-AP42VG(K)".

Let me know if there is something I can do to help.

/David

**Comment by XattSPT** [comment]
Hi @DavidDjerf i've published a test version at:

https://homey.app/a/com.mecloud/test/

can you try if it solves the problem?

If not, can you do a couple of things for me?
1) set your device update time (on settings/advanced settings) to 1 minute.
2) after 5-10 minutes, send me a diagnostic report on More/Applications/Melcloud then settings and send diagnostic report?

thanks in advance.

**Comment by DavidDjerf** [comment]
I installed the beta version and restarted the app, set update to 1 minutes.
If I run my flow that only set "vertical swing" to middle top, the horisontal swing turns into auto.
Also, if I run the flow that sets horisontal swin g to middle left, it also sets the vertical swing to middle top, and horisontal swing turns into auto.

I sent you a diagnostics report: e2d44f4e-7ed5-4284-85a2-23f7ceded4a0

**Comment by XattSPT** [comment]
Thanks, I see the bug. I’ll try to publish a test tomorrow o thursday to
check if solves the error.

I do not have horitzontal options so I’ve not test!

Problems in vertical are also related to same bug.

Thanks again for your report! Has been very fruitful!

El dt, 2 juny 2020 a les 20:11 DavidDjerf <notifications@github.com> va
escriure:

**Comment by XattSPT** [comment]
@DavidDjerf I've published a new test. 

I think I've solved the bug, but my device is always set to middle on horizontal position, I think is coused because I do not have this option. 

If you can try and tell me how it works.  

Vertical movement does not interfere now in horizontal settings.... 

Thanks in advance,

G.

**Comment by DavidDjerf** [comment]
I was about tro reply some test result to you but they results changes so I have to do a better test logg to see what is going on. I will also try to increase the time between commands to see that its not a flooding issue. Ill get back to you ASAP!

**Comment by DavidDjerf** [comment]
Here is my findings:
![melcloud_debug](https://user-images.githubusercontent.com/39162087/84827694-2046a280-b025-11ea-8879-4897b61470a5.png)

Btw, bottom is spelled incorrectly, "botom" in the app. Must be a typo.

**Comment by XattSPT** [comment]
It will be a new version in a copuple of days. 

Hope this should be solved. 

Thanks.
